### ISSUE TITLE
Updating content fields

### ISSUE THREAD

**Issue by ronnqvistandreas** [RWS/dxa-flexible-campaign-content#8]
Is there a reason for not updating content fields after the first time a zip is uploaded? 

```c#
if ( taggedContentList.Values.Count > 0 || taggedImageList.Values.Count > 0 )
{
    // Just do the extraction of content fields from the HTML the first time
    //
    return;
}
```

The only way for an editor to change the look and feel of a campaign, or to change the number of images that should appear, is to make the changes to the html and then upload the zip again. We're currently forced to create new components whenever we make a change to a zip, adding or removing content fields.

**Comment by NiclasCedermalm** [comment]
The main reason for not updating the content fields is to avoid override texts that editors might have updated. You can update the ZIP file in the component (for example if changing HTML, CSS, JS etc) and republish the component and your changes should take effect (as DXA caches binaries you might need to clear the DXA cache to see the changes). However one improvement could be that new fields (tagged content, properties etc) could be detected and those are added to the multimedia component when uploading a new ZIP file to the multimedia component.

**Comment by ronnqvistandreas** [comment]
Would that improvement be something that could be implemented?

**Comment by NiclasCedermalm** [comment]
Sure. I'll add the possibility to detect new fields for the 1.2 release.

**Comment by NiclasCedermalm** [comment]
Is now supported in v1.3.2.
